# Generated by Django 5.2.6 on 2025-09-12 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherapplication',
            old_name='message',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='teacher_resumes/'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='expertise',
            field=models.CharField(help_text='e.g., Physics, Calculus, IELTS', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='teacherapplication',
            unique_together={('user', 'status')},
        ),
    ]
