# Generated by Django 5.2.6 on 2025-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_message_teacherapplication_bio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherapplication',
            unique_together=set(),
        ),
    ]
