# Generated by Django 5.2.6 on 2025-10-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming-tech', 'Programming & Tech'), ('graphics-design', 'Graphics & Design'), ('digital-marketing', 'Digital Marketing'), ('writing-translation', 'Writing & Translation'), ('video-animation', 'Video & Animation'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
