# Generated by Django 5.2.7 on 2025-10-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassenrollment',
            name='instructor_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveclassenrollment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
