# Generated by Django 5.2.7 on 2025-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_liveclassenrollment_instructor_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassenrollment',
            name='first_message_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
