# Generated by Django 5.2.7 on 2025-10-17 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_liveclassenrollment_first_message_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='category',
            field=models.CharField(choices=[('programming-tech', 'Programming & Tech'), ('business', 'Business'), ('design-creative', 'Design & Creative'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
